# 10_DL from scratch - 간단한 학습 원리

In [2]:
import numpy as np

X = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1]
])

# 활성함수로 sigmoid를 만듦
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


# 가중치를 랜덤하게 선택
## 원래는 학습이 완료된 가중치를 사용해야 한다.
W = 2 * np.random.random((1,3)) - 1
        # np.random.random((n,m)) : 양수만 나온다.
    # 2를 곱하고
                                # -1을 해주면 음수 양수 골고루 나온다.
W


# 추론결과
N = 4
# 데이터가 4개가 있기 때문에 4로 지정함.
for k in range(N):
    x = X[k, :].T
        # k행의 모든 열을 가져옴.
                # T : transpose
    v = np.matmul(W, x)
            # matmul : matrics multiplics // 행렬의 곱의 합
    y = sigmoid(v)

    print(y)

[-0.42829416]
[0.47080762]
[0.44213849]
[1.34124027]


>> 가중치 (W)가 `랜덤`으로 받은것이기 때문에 정답을 맞출 수 없다.

In [3]:
# 가중치가 이제 정답을 맞추도록 학습을 시켜야 한다.
# 1. 정답을 알려주기
import numpy as np

X = np.array([[0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]])

D = np.array([[0],[0],[1],[1]])

![](./lecture_image/10-01.png)

![](./lecture_image/10-02.png)

![](./lecture_image/10-03.png)

In [4]:
# 일단 모델의 출력을 계산하는 함수
def calc_output(W,x):
    v = np.matmul(W, x)
    y = sigmoid(v)

    return y

In [5]:
# 오차를 계산
def calc_error(d, y):
            # d : 정답
                # y : 추론값
    e = d - y
    # e : 오차 (정답 - 추론값)
    delta = y * (1-y) * e
            # 에러와 활성화 함수의 미분값이 적용하는 것.

    return delta

In [8]:
# 시그모이드의 미분
import sympy as sym

z = sym.Symbol('z')
        # 'z'를 심볼릭으로 넣음.
s = 1 / (1 + sym.exp(-z))

sym.diff(s)

exp(-z)/(1 + exp(-z))**2

In [9]:
# 한 epoch에 수행되는 W의 계산
def delta_GD(W, X, D, alpha):
        # GD : Gradient Decent
    for k in range(4):
        x = X[k, :].T
        d = D[k]

        y = calc_output(W, x)
        delta = calc_error(d, y)

        dW = alpha*delta*x
        # 가중치 변화량
        W = W + dW

    return W

In [10]:
# 가중치를 랜덤하게 초기화하고 학습 시작
W = 2 * np.random.random((1,3)) - 1

In [11]:
alpha = 0.9
# 학습률
for epoch in range(10000):
    W = delta_GD(W, X, D, alpha)
    print(W)

[[ 0.92709098 -0.25823307 -0.40401388]]
[[ 1.11403373 -0.22288667 -0.36656804]]
[[ 1.2711255  -0.20703293 -0.36620146]]
[[ 1.40736076 -0.20263331 -0.38780409]]
[[ 1.52886915 -0.20444681 -0.4215904 ]]
[[ 1.63949363 -0.20937553 -0.4617093 ]]
[[ 1.74165649 -0.21565295 -0.50473202]]
[[ 1.83693847 -0.22229767 -0.54866503]]
[[ 1.92641923 -0.2287841  -0.59236184]]
[[ 2.01087316 -0.23484879 -0.6351776 ]]
[[ 2.09088267 -0.24037719 -0.67676553]]
[[ 2.16690496 -0.24533759 -0.71695599]]
[[ 2.23931217 -0.24974276 -0.75568436]]
[[ 2.30841621 -0.25362774 -0.79294756]]
[[ 2.37448444 -0.25703731 -0.8287779 ]]
[[ 2.43775003 -0.26001887 -0.86322718]]
[[ 2.49841894 -0.26261868 -0.89635707]]
[[ 2.5566749  -0.26487997 -0.92823337]]
[[ 2.61268297 -0.26684213 -0.95892247]]
[[ 2.66659231 -0.26854049 -0.98848937]]
[[ 2.71853832 -0.2700064  -1.01699651]]
[[ 2.76864434 -0.27126756 -1.04450322]]
[[ 2.81702309 -0.2723483  -1.07106541]]
[[ 2.86377782 -0.27327    -1.09673553]]
[[ 2.90900337 -0.27405138 -1.12156266]]


In [13]:
N = 4
for k in range(N):
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)

    print(y)

[0.01019741]
[0.00829294]
[0.99324297]
[0.99168827]


> 시그모이드의 결과가 `[[0],[0],[1],[1]]` 이라는 정답을 맞췄다. `(0의 근사값 2, 1의 근사값 2)`