# 54_RNN - simple RNN


# simple RNN :
### - 순환신경망
- 활성화 신호가 입력에서 출력으로 한 방향으로 흐르는 피드포워드 신경망
- 순환 신경망은 뒤쪽으로 연결하는 순환 연결이 있음
- 순서가 있는 데이터를 입력으로 받고
- 변화하는 입력에 대한 출력을 얻음

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# time stamp 데이터 만들기
X = []
Y = []
for i in range(6):

    lst = list(range(i, i+4))

    X.append(list(map(lambda c: [c/10], lst)))
                        # lambda c :
                            # c = [x/10 for x in lst]
    Y.append((i+4)/10)

X = np.array(X)
Y = np.array(Y)
for i in range(len(X)):
    print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9
