# 54_RNN - simple RNN


# simple RNN :
### - 순환신경망
- 활성화 신호가 입력에서 출력으로 한 방향으로 흐르는 피드포워드 신경망
- 순환 신경망은 뒤쪽으로 연결하는 순환 연결이 있음
- 순서가 있는 데이터를 입력으로 받고
- 변화하는 입력에 대한 출력을 얻음

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# time stamp 데이터 만들기
X = []
Y = []
for i in range(6):

    lst = list(range(i, i+4))

    X.append(list(map(lambda c: [c/10], lst)))
                        # lambda c :
                            # c = [x/10 for x in lst]
    Y.append((i+4)/10)

X = np.array(X)
Y = np.array(Y)
for i in range(len(X)):
    print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [3]:
# simple RNN 구성하기
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units = 10, return_sequences=False, input_shape=[4,1]),
                                            # return_sequences : 단이 하나이기 때문에 출력만 뽑아서 보려고 False 를 설정
                                            # 여러개의 SimpleRNN 을 사용하는 경우 출력단을 제외하고 모두 True를 사용함
    tf.keras.layers.Dense(1)
])

model.compile(optimizer = 'adam', loss='mse')
model.summary()

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-06-23 15:36:12.425203: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-23 15:36:12.426561: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 10)                120       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [4]:
# Fit
model.fit(X, Y, epochs=100, verbose=0)

2022-06-23 15:37:22.542663: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-06-23 15:37:23.222566: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [5]:
# predict
model.predict(np.array([[[0.6], [0.7],[.8],[.9]]]))

2022-06-23 15:38:00.351758: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 1s 502ms/step


array([[0.907671]], dtype=float32)

In [6]:
model.predict(np.array([[[-.1],[.0],[.1],[.2]]]))

1/1 [==============================] - 0s 26ms/step


array([[0.41998538]], dtype=float32)

-----------------------
# 모델 더 손보기

In [7]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=10, return_sequences=True, input_shape=[4,1]),
                                        # return_sequences : 해당 출력단의 결과를 다음 layer로 보냄(True)
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)    
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 4, 10)             120       
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 4, 10)             210       
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 4, 10)             210       
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 10)                210       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 761
Trainable params: 761
Non-trainable params: 0
_________________________________________________________________


In [8]:
# fit
model.fit(X, Y, epochs=100, verbose=1)

Epoch 1/100


2022-06-23 15:41:36.226340: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 2s 2s/step - loss: 3.2902
Epoch 2/100
1/1 [==============================] - 0s 111ms/step - loss: 2.8019
Epoch 3/100
1/1 [==============================] - 0s 111ms/step - loss: 2.3177
Epoch 4/100
1/1 [==============================] - 0s 131ms/step - loss: 1.8482
Epoch 5/100
1/1 [==============================] - 0s 93ms/step - loss: 1.4060
Epoch 6/100
1/1 [==============================] - 0s 93ms/step - loss: 1.0051
Epoch 7/100
1/1 [==============================] - 0s 102ms/step - loss: 0.6600
Epoch 8/100
1/1 [==============================] - 0s 88ms/step - loss: 0.3836
Epoch 9/100
1/1 [==============================] - 0s 109ms/step - loss: 0.1842
Epoch 10/100
1/1 [==============================] - 0s 85ms/step - loss: 0.0631
Epoch 11/100
1/1 [==============================] - 0s 85ms/step - loss: 0.0124
Epoch 12/100
1/1 [==============================] - 0s 96ms/step - loss: 0.0165
Epoch 13/100
1/1 [==============================] - 0s 80m

In [9]:
model.predict(np.array([[[.6],[.7],[0.8],[.9]]]))

1/1 [==============================] - 0s 353ms/step


2022-06-23 15:42:12.556133: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.7825213]], dtype=float32)