# Tensor 다루기 

In [1]:
import torch

PyTorch에서는 Tensor type이 Variable과 Constant를 포함합니다. 

기존에는 Variable 타입이 있었지만, 이는 자동미분을 위한 것이었는데, 이 기능을 Tensor 타입에 포함 시켰습니다. 

#### 기존의 데이터를 Torch의 Tensor로

In [9]:
li = [[1, 2], [3, 4]]

li_tensor = torch.tensor(li)
li_as_tensor = torch.as_tensor(li)

print(li_tensor)
print(li_tensor.shape)
print(li_tensor.dtype)
print("-" * 10)
print(li_as_tensor)
print(li_as_tensor.shape)
print(li_as_tensor.dtype)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
----------
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


In [14]:
arr = np.array([[1, 2], [3, 4]])

arr_tensor = torch.tensor(arr)
arr_as_tensor = torch.as_tensor(arr)
arr_from_numpy = torch.from_numpy(arr)

print(arr_tensor)
print(arr_tensor.shape)
print(arr_tensor.dtype)
print("-" * 10)
print(arr_as_tensor)
print(arr_as_tensor.shape)
print(arr_as_tensor.dtype)
print("-" * 10)
print(arr_from_numpy)
print(arr_from_numpy.shape)
print(arr_from_numpy.dtype)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
----------
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
----------
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


#### torch의 Tensor의 속성값 확인

In [20]:
li_tensor.shape

torch.Size([2, 2])

In [19]:
li_tensor.size()

torch.Size([2, 2])

#### torch를 numpy 배열로

In [13]:
print(li_tensor.numpy())
print(arr_as_tensor.numpy())
print(arr_from_numpy.numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


#### 특정한 값의 Tensor 생성하기

In [16]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
torch.ones(5), torch.zeros(5) 

(tensor([1., 1., 1., 1., 1.]), tensor([0., 0., 0., 0., 0.]))

In [21]:
torch.ones(5), torch.zeros(5) 

(tensor([1., 1., 1., 1., 1.]), tensor([0., 0., 0., 0., 0.]))

In [28]:
torch.ones_like(li_tensor), torch.zeros_like(li_tensor)#, torch.zeros_like(arr) -> Tensor를 입력해야함. 

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0, 0],
         [0, 0]]))

In [22]:
torch.linspace(0, 10,  5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [23]:
torch.logspace(0, 10,  5)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

#### 난수 생성하기

In [2]:
# seed 조절 하기!!
torch.manual_seed(7777)

In [31]:
a = torch.rand(5)#균등분포
b = torch.randn(5)#Normal 분포 
c = torch.randint(10, size=(5,))
print(a, b, c, sep="\n")

tensor([0.5263, 0.2437, 0.5846, 0.0332, 0.1387])
tensor([ 0.8512, -0.3502,  1.6881, -2.1575, -1.3927])
tensor([6, 6, 7, 9, 6])


### 데이터 타입

In [50]:
torch.randint(10, size=(5,), dtype=torch.float32)

tensor([5., 7., 2., 5., 6.])

`tensor_var.type()` -> inplace 명령이 아님

In [51]:
a = torch.randint(10, size=(5,))
print(a.dtype)

print(a.type(torch.float32))
print(a.dtype)

a = a.type(torch.float64)
print(a.dtype)

torch.int64
tensor([6., 5., 4., 0., 8.])
torch.int64
torch.float64


#### GPU 사용하기

Torch에서는 GPU 사용을 위해서 데이터 타입을 변환해줘야함. 

In [3]:
torch.cuda.is_available()

False

GPU가 사용 가능한 환경에서는

![](../../statics/imgs/torch_cuda.png)

GPU 를 사용하기 위해 Cuda에서 사용하는 데이터타입으로 바꾸어줘야 한다. 

방법 세가지! 

 - 만들 때, device 설정해두기
 - tensor_var.cuda()
 - tensor_var.to(device)


In [49]:
# device 설정하기.
x = torch.ones(2, 2, device='cuda')

# 여러개 중에 하나의 GPU에 할당하고 싶을 때
# 번호는 nvidia-smi 명령을 Shell에 입력해서 찾을 수 있음 
x = torch.ones(2, 2, device='cuda:0')

# device 객체를 입력하는게 기본
x = torch.ones(2, 2, device=torch.device('cuda'))

In [55]:
# .cuda()
a = torch.rand(10)
print(a)

a = a.cuda()
print(a)

torch.float32


In [57]:
# .to(device)
a = torch.rand(2)
print(a)

a = a.to("cuda")
print(a)

In [ ]:
a = torch.rand(2)
print(a)

a = a.to(torch.device("cuda"))
print(a)

대부분 그냥 이렇게 사용합니다! 

In [58]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

a = torch.rand(2)
print(a)

a = a.to(device)
print(a)

cpu
tensor([0.1168, 0.0321])
tensor([0.1168, 0.0321])
