# 텐서 연산

In [1]:
import torch

### 기본 연산

In [2]:
x = torch.arange(0, 5)
y = torch.arange(1, 6)

In [4]:
type(x)
    # tensor 형태

torch.Tensor

In [5]:
print(x + y)
print(torch.add(x, y))
print(x.add(y))

tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


In [6]:
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])


In [7]:
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([ 0,  2,  6, 12, 20])
tensor([ 0,  2,  6, 12, 20])
tensor([ 0,  2,  6, 12, 20])


In [8]:
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])
tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])
tensor([0.0000, 0.5000, 0.6667, 0.7500, 0.8000])


In [9]:
print(x**y)
print(torch.pow(x, y))
print(x.pow(y))

tensor([   0,    1,    8,   81, 1024])
tensor([   0,    1,    8,   81, 1024])
tensor([   0,    1,    8,   81, 1024])


In [10]:
print(-x)
print(torch.negative(x))
print(x.negative())

tensor([ 0, -1, -2, -3, -4])
tensor([ 0, -1, -2, -3, -4])
tensor([ 0, -1, -2, -3, -4])


* `torch.abs`: 절대값
* `torch.sign`: 부호
* `torch.round`: 반올림
* `torch.ceil`: 올림
* `torch.floor`: 내림
* `torch.square`: 제곱
* `torch.sqrt`: 제곱근
* `torch.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `torch.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `torch.cumsum`: 누적합
* `torch.cumprod`: 누적곱


> #### Tensorflow에서 배운 연산 함수와 같음
-----------------

In [11]:
print(torch.abs)
print(torch.sign)
print(torch.round)
print(torch.ceil)
print(torch.floor)
print(torch.square)
print(torch.sqrt)
print(torch.maximum)
print(torch.minimum)
print(torch.cumsum)
print(torch.cumprod)

<built-in method abs of type object at 0x1060248c8>
<built-in method sign of type object at 0x1060248c8>
<built-in method round of type object at 0x1060248c8>
<built-in method ceil of type object at 0x1060248c8>
<built-in method floor of type object at 0x1060248c8>
<built-in method square of type object at 0x1060248c8>
<built-in method sqrt of type object at 0x1060248c8>
<built-in method maximum of type object at 0x1060248c8>
<built-in method minimum of type object at 0x1060248c8>
<built-in method cumsum of type object at 0x1060248c8>
<built-in method cumprod of type object at 0x1060248c8>


#### 차원 축소 연산
PyTorch는 기본이 reduce 연산

In [14]:
x = torch.randint(10, size=(5, 2, 4))
                            # axis(dim)=0 에서 5개
                                # axis(dim)=1 에서 2개
                                    # axis(dim)=2 에서 4개의 elements(원소)가 있다
print(x.shape)
print(x)

torch.Size([5, 2, 4])
tensor([[[6, 4, 7, 6],
         [6, 8, 0, 6]],

        [[0, 0, 0, 3],
         [2, 7, 7, 0]],

        [[4, 2, 0, 8],
         [6, 2, 3, 1]],

        [[4, 1, 3, 6],
         [5, 3, 4, 0]],

        [[8, 1, 5, 7],
         [6, 5, 3, 6]]])


In [15]:
print(torch.sum(x))
print(torch.sum(x).shape)
print(torch.sum(x, dim=1))
print(torch.sum(x, dim=1).shape)
print(torch.sum(x, dim=2))
print(torch.sum(x, dim=2).shape)

tensor(155)
torch.Size([])
tensor([[12, 12,  7, 12],
        [ 2,  7,  7,  3],
        [10,  4,  3,  9],
        [ 9,  4,  7,  6],
        [14,  6,  8, 13]])
torch.Size([5, 4])
tensor([[23, 20],
        [ 3, 16],
        [14, 12],
        [14, 12],
        [21, 20]])
torch.Size([5, 2])


#### 행렬 연산

In [18]:
a = torch.tensor([[2, 0], [0, 1]], dtype=torch.float32)
b = torch.tensor([[1, 1], [1, 1]], dtype=torch.float32)
a, b

(tensor([[2., 0.],
         [0., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [20]:
torch.matmul(a, b), torch.mm(a,b)
                          # mm 도 자주 쓰인다.

(tensor([[2., 2.],
         [1., 1.]]),
 tensor([[2., 2.],
         [1., 1.]]))

In [21]:
torch.linalg.inv(a)

tensor([[0.5000, -0.0000],
        [0.0000, 1.0000]])

### 크기와 차원을 바꾸는 명령 
 - `torch.reshape`
 - `.view`
 - `torch.transpose`

In [23]:
# view  함수는 이렇게 못씀
torch.view(a, (4, -1)) 
        # tensor의 맴버 함수로 view가 들어가기 때문에, torch에서는 못쓴다(?)
        # a.view 를 사용한다.

AttributeError: module 'torch' has no attribute 'view'

In [24]:
print(a.view(4, -1), a.view((4, -1)), sep="\n")
print(a.view(4, -1).shape, a.view((4, -1)).shape)

tensor([[2.],
        [0.],
        [0.],
        [1.]])
tensor([[2.],
        [0.],
        [0.],
        [1.]])
torch.Size([4, 1]) torch.Size([4, 1])


In [25]:
torch.reshape(a, (4, -1))

tensor([[2.],
        [0.],
        [0.],
        [1.]])

view 함수와 reshape 함수가 기능이 똑같다. 
-----------

In [26]:
# view함수가 있어 expand_dims 같은 함수가 따로 필요없다. 
a.view((1, 4, 1)), a.view((1, 4, 1)).shape

(tensor([[[2.],
          [0.],
          [0.],
          [1.]]]),
 torch.Size([1, 4, 1]))

In [27]:
print(torch.squeeze(a.view((1, 4, 1)), dim=2))
print(torch.squeeze(a.view((1, 4, 1)), dim=2).shape)

tensor([[2., 0., 0., 1.]])
torch.Size([1, 4])


- expand_dims 함수 대신에 unsqueeze 함수가 있다. 
----------------------

In [28]:
print(torch.unsqueeze(a.view((1, 4)), dim=2))
print(torch.unsqueeze(a.view((1, 4)), dim=2).shape)

tensor([[[2.],
         [0.],
         [0.],
         [1.]]])
torch.Size([1, 4, 1])


##### 여러 함수가 torch.명령어 형태, tensor.명령어 로  사용 할 수 있다. 

In [92]:
a = torch.arange(10).view(5, 2)

In [95]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [93]:
a.transpose(1, 0)

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [94]:
torch.transpose(a, 1, 0)

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

#### 함수 끝에 `_`를 붙이면 inplace명령이 된다.(안되는 함수가 존재함)

In [96]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [29]:
print(a)
print(a.transpose_(0, 1))
            # _를 붙이면 inplace(변화, 교체)되어 저장된다.
            # 원래는 저장되지 않음.
print(a)

tensor([[2., 0.],
        [0., 1.]])
tensor([[2., 0.],
        [0., 1.]])
tensor([[2., 0.],
        [0., 1.]])


In [30]:
a.shape

torch.Size([2, 2])

### transpose 하고 view  했을 때 이런 에러가 발생하기도 한다. 

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


이는 PyTorch가 데이터를 메모리에 저장하는 방식과 view, reshape, transpose 연산들이 연산을 수행하는 방식의 차이에 기인한다. 
메모리상의 데이터의 물리적 위치와 index가 일치 할 때 contiguous 하다고 표현하는데, view는 contiguous해야만 연산을 수행할 수 있다. 

이를 해결하기위해 tensor.contiguous() 함수를 호출하여 데이터를 정리해주면 된다. 근데! 이런 이슈는 가끔 나오는 거니 어려우면 지금은 그냥 넘어가도 좋다!!!!

In [ ]:
# a = a.contiguous()

In [31]:
# view함수에는 inplace명령이 구현되어 있지 않다. 
print(a.view(-1, 1), a.view(-1, 1).shape)
print(a.view_())
print(a)

# Use .reshape(...) instead.

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

#### 형상 연산 중 유용한 것

In [108]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [110]:
b = torch.arange(10).view(2, 5)
b

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [114]:
# a = a.contiguous()

In [115]:
print(a.view_as(b))
print(a.reshape_as(b))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### indexing, slicing

In [116]:
a[0]

tensor([0, 1])

In [117]:
a[0, 1]

tensor(1)

In [119]:
a[4, 1]

tensor(9)

In [120]:
a[:2]

tensor([[0, 1],
        [2, 3]])

### **텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

#### 나누는 연산

In [125]:
c = torch.rand(3, 6)
c

tensor([[0.9248, 0.4310, 0.1193, 0.5057, 0.8501, 0.5508],
        [0.7222, 0.5667, 0.4905, 0.5927, 0.2890, 0.4687],
        [0.1016, 0.5755, 0.6283, 0.0573, 0.1862, 0.2670]])

In [126]:
c1, c2, c3 = torch.chunk(c, 3, dim=1)
                    # 나눈다
                            # 3개로
                                
print(c1)
print(c2)
print(c3)

tensor([[0.9248, 0.4310],
        [0.7222, 0.5667],
        [0.1016, 0.5755]])
tensor([[0.1193, 0.5057],
        [0.4905, 0.5927],
        [0.6283, 0.0573]])
tensor([[0.8501, 0.5508],
        [0.2890, 0.4687],
        [0.1862, 0.2670]])


In [127]:
c1, c2, c3 = torch.chunk(c, 3, dim=0)
print(c1)
print(c2)
print(c3)

tensor([[0.9248, 0.4310, 0.1193, 0.5057, 0.8501, 0.5508]])
tensor([[0.7222, 0.5667, 0.4905, 0.5927, 0.2890, 0.4687]])
tensor([[0.1016, 0.5755, 0.6283, 0.0573, 0.1862, 0.2670]])


In [138]:
torch.split(c, 1, dim=0)

(tensor([[0.9248, 0.4310, 0.1193, 0.5057, 0.8501, 0.5508]]),
 tensor([[0.7222, 0.5667, 0.4905, 0.5927, 0.2890, 0.4687]]),
 tensor([[0.1016, 0.5755, 0.6283, 0.0573, 0.1862, 0.2670]]))

In [141]:
torch.split(c, 2, dim=1)

(tensor([[0.9248, 0.4310],
         [0.7222, 0.5667],
         [0.1016, 0.5755]]),
 tensor([[0.1193, 0.5057],
         [0.4905, 0.5927],
         [0.6283, 0.0573]]),
 tensor([[0.8501, 0.5508],
         [0.2890, 0.4687],
         [0.1862, 0.2670]]))

In [142]:
torch.split(c, 3, dim=1)

(tensor([[0.9248, 0.4310, 0.1193],
         [0.7222, 0.5667, 0.4905],
         [0.1016, 0.5755, 0.6283]]),
 tensor([[0.5057, 0.8501, 0.5508],
         [0.5927, 0.2890, 0.4687],
         [0.0573, 0.1862, 0.2670]]))

#### 결합하는 연산

In [144]:
a = torch.ones(2, 3)
b = torch.zeros(3, 3)
a, b

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [32]:
torch.cat([a, b], dim=0)
        # tf.concat()

tensor([[2., 0.],
        [0., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
torch.cat([a, b], dim=1)

tensor([[2., 0., 1., 1.],
        [0., 1., 1., 1.]])

In [167]:
a = torch.ones_like(b)
a, a.size()

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 3]))

In [168]:
b, b.size()

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([3, 3]))

In [169]:
torch.stack([a, b], dim=1), torch.stack([a, b], dim=1).size()

(tensor([[[1., 1., 1.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [0., 0., 0.]]]),
 torch.Size([3, 2, 3]))

In [171]:
torch.stack([a, b], dim=0), torch.stack([a, b], dim=0).size()

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([2, 3, 3]))

In [172]:
torch.stack([a, b], dim=2), torch.stack([a, b], dim=2).size()

(tensor([[[1., 0.],
          [1., 0.],
          [1., 0.]],
 
         [[1., 0.],
          [1., 0.],
          [1., 0.]],
 
         [[1., 0.],
          [1., 0.],
          [1., 0.]]]),
 torch.Size([3, 3, 2]))

In [182]:
torch.tile(a, (3, 1))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [184]:
torch.tile(a, (1, 2))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [150]:
torch.vstack

<function _VariableFunctionsClass.vstack>

In [151]:
torch.hstack

<function _VariableFunctionsClass.hstack>