# Variable

In [6]:
import tensorflow as tf
import numpy as np

<h4> Variable (변수)</h4>

- 미지수, 가중치를 정의할 때 사용
- 직접 사용할 일이 많지는 않음

- 변수 정의는 변수 생성 + 초기화

In [7]:
tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
arr = np.array([[1, 2], [3, 4]])
li = [[1, 2], [3, 4]]

te_var = tf.Variable(tensor)
arr_var = tf.Variable(arr)
li_var = tf.Variable(li)

print(te_var)
print(arr_var)
print(li_var)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


- Constant와 같이 기본 속성값이 들어있음. 

In [11]:
print("Shape: ", te_var.shape)
print("DType: ", te_var.dtype)
print("As NumPy: ", te_var.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [14]:
print('shape : ', arr_var.shape)
print('dtype : ', arr_var.dtype)
print('as numpy : ', arr_var.numpy())

shape :  (2, 2)
dtype :  <dtype: 'int64'>
as numpy :  [[1 2]
 [3 4]]


In [15]:
print('shape : ', li_var.shape)
print('dtype : ', li_var.dtype)
print('as numpy : ', li_var.numpy())

shape :  (2, 2)
dtype :  <dtype: 'int32'>
as numpy :  [[1 2]
 [3 4]]


### 변수는 기존 텐서의 메모리를 재사용하여 텐서를 재할당 할 수 있다. 


In [12]:
a = tf.Variable([2.0, 3.0])
print("First : ", a, "\n")

a.assign([1, 2])        # 똑같은 형태의, 하지만 값은 다른 것을 설정함. 
                        # 해당 줄의 경우 int 값을 넣었지만, float32 값으로 재설정되어 들어감
print("Second : ", a, "\n")


First :  <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)> 

Second :  <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)> 



In [13]:
# 기존 메모리의 크기와 다르면 할당 할 수 없음! 
a.assign([1.0, 2.0, 3.0]) 

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.