# Constants

In [74]:
import tensorflow as tf

In [75]:
import numpy as np

## Tensor

- Deeplearning framework는 기본적으로 Tensor를 다루는 도구다.
    - [Tensor](https://www.google.com/search?q=Tensor&newwindow=1&sxsrf=AOaemvLxCRvi46j5dRtWwY8K6ssvkpF48A:1641452781782&source=lnms&tbm=isch&sa=X&ved=2ahUKEwin2eSPyJz1AhXNdd4KHWzUAd8Q_AUoAXoECAIQAw&biw=1440&bih=820&dpr=2)


- Tensor를 다룰 때 가장 중요한 것! 

  ${\rightarrow} \ $ **SHAPE !!!**
  
 (해보면 알겠지만, 제일 에러 많이 나는 이유, 제일 헷갈리는 것, 개발할 때 우리가 이론을 알아야 하는 이유, 함수들의 설정값을 확인해야하는 이유)
 
 

## Tensor 생성

우리가 생성하는 것은 `tf.Tensor` 데이터!

**항상 체크 해야 할 것 !**
 - shape
 - dtype (데이터 타입이 같아야 연산이 가능합니다.)

<h4> Constant (상수)</h4>

- **```tf.constant()```**

    - list -> Tensor
    - tuple -> Tensor
    - Array -> Tensor

In [76]:
li_ten = tf.constant([1, 2, 3])
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [77]:
li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [78]:
tu_ten = tf.constant(((1, 2, 3), (1, 2, 3)), name="sample")
tu_ten

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [79]:
arr = np.array([1., 2., 3.])#, dtype='float64')
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

#### 잠깐 옆으로 새서...
* double precision : 64bits
* single precision : 32bits
* half precision   : 16bits

### Numpy array 추출

In [80]:
arr_ten.numpy(), type(arr_ten.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [81]:
li_ten.numpy(), type(li_ten.numpy())

(array([1, 2, 3], dtype=int32), numpy.ndarray)

In [82]:
not_a_matrix = [[1,2,3], [4, 5], [6, 7, 8]]
# tf.constant(not_a_matrix)

# ValueError: Can't convert non-rectangular Python sequence to Tensor.
## 3개의 shape 가 맞지 않아서 발생하는 오류

In [83]:
# 3개가 같은 shape 이면 constant 된다.
a_matrix = [[1,2,3], [4,5,6], [7,8,9]]
tf.constant(a_matrix)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

### shape, dtype 항상 체크!!

In [84]:
li_ten.shape, tu_ten.shape

(TensorShape([3]), TensorShape([2, 3]))

In [85]:
arr_ten.dtype, li_ten.dtype

(tf.float64, tf.int32)

In [86]:
# 1번 케이스
# tf.matmul(li_ten, tu_ten)       # matmul : 3차원 이상의 텐서 사이의 행렬 곱
# InvalidArgumentError: In[0] and In[1] has different ndims: [3] vs. [2,3] [Op:MatMul]

# shape 가 달라셔 발생하는 오류 // 디비전이 안맞아서 내적이 불가능하다.

In [87]:
# 2번 케이스
# tf.matmul(tu_ten, li_ten)       # 랭크 수(차원)가 안맞아서 불가능하다. // 랭크수를 맞추면 가능함.

In [88]:
# 랭크 수(차원)를 확인하는 명령어 : .ndim
print(li_ten.shape, li_ten.ndim)        # 1차원
print(tu_ten.shape, tu_ten.ndim)        # 2차원

(3,) 1
(2, 3) 2


In [89]:
# 3번 케이스
# arr_ten * li_ten

# InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a int32 tensor [Op:Mul]
# dtype 이 달라서 문제가 생김.

In [90]:
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [91]:
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

# 데이터 타입 컨트롤하는 방법
  - `tf.cast`

In [92]:
# 미리 지정해주거나
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [93]:
# tf.cast를 사용. 다만, 많은 경우 미리 데이터타입을 정리해둘 수 있다.
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

#### 간단 퀴즈 

아래 코드를 에러 없이 실행 하시오. 

In [94]:
arr_ten, li_ten

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

In [95]:
arr_ten * li_ten        # dtype이 달라서 생기는 문제

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a int32 tensor [Op:Mul]

------

In [ ]:
arr_ten = tf.cast(arr_ten, dtype=tf.int32)          # arr_ten 의 dtype을 int32로 바꾸기
arr_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
arr_ten * li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

### 특정 값의 Tensor 생성

 - `tf.ones`
 - `tf.zeros`
 - `tf.range`


In [ ]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [ ]:
tf.zeros((2, 5), dtype="int32")

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.range(1, 11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

####  간단 퀴즈

**n 을 입력하면 첫항이 1이고 공비가 2인 등비수열을 생성하는 함수를 만드시오** 
(이 때 결과값은 tf.Tensor 데이터이고, 데이터 타입은 tf.int32)

$$
n = 10 \ 일 때 \\ \\
(1, 2, 4, 8, 16, 32, 64, 128, 256, 512)
$$

In [ ]:
def geometric_sequence(n):      # n 은 출력하는 갯수
    pass

In [ ]:
def geometric_sequence(n):
    answer = tf.range(1, n, 2, dtype=tf.int32)

    return answer

In [ ]:
print(geometric_sequence(10))

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


-----

In [ ]:
def geometric_sequence(n):
    r = tf.range(n, dtype=tf.int32)   #, dtype='int32')
    s = tf.ones(n, dtype=tf.int32) * 2

    print('r :', r)
    print('s :', s)
    return s ** r

In [ ]:
print(geometric_sequence(10))

r : tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
s : tf.Tensor([2 2 2 2 2 2 2 2 2 2], shape=(10,), dtype=int32)
tf.Tensor([  1   2   4   8  16  32  64 128 256 512], shape=(10,), dtype=int32)


<h4> Random Value(난수)</h4>

- 무작위 값을 생성할 때 필요. 
- Noise를 재현 한다거나, test를 한다거나 할 때 많이 사용됨 
- 데이터 타입은 상수형태로 반환됨

**`tf.random`** 에 구현 되어 있음. 

  - `tf.random.normal`
      - Gaussian Normal Distribution
      
  - `tf.random.uniform`
      - Uniform Distribution
      
> 이렇게나 많습니다! [LINK](https://www.tensorflow.org/api_docs/python/tf/random)

In [ ]:
shape = (3, 3)

In [ ]:
tf.random.normal(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1884669 ,  0.04629149,  0.035827  ],
       [ 1.9526739 ,  0.6173512 , -0.6373802 ],
       [-0.25540426, -0.17338702, -0.67253745]], dtype=float32)>

In [ ]:
tf.random.normal(shape, mean=100, stddev=10) #100 을 평균으로하고, 표준편차를 10으로 한 값

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[101.76931 ,  85.457726,  95.54172 ],
       [ 79.530304,  98.56057 ,  89.69934 ],
       [ 87.74518 ,  89.28386 , 121.190025]], dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [ ]:
tf.random.uniform(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.4063989 , 0.16350043, 0.49475944],
       [0.41444743, 0.7097274 , 0.43024313],
       [0.8637649 , 0.6725483 , 0.09786201]], dtype=float32)>

* **Random seed 관리 하기!!!**

 - Random value로 보통 가중치를 초기화 
 - 이외에도 학습과정에서 Random value가 많이 사용됨. 
 - 이를 관리 안해주면, 자신이 했던 작업이 동일하게 복구 또는 재현이 안됨!!! 
 
 
- **`tf.random.set_seed({seed_number})`**

 
**=> 재현성 유지를 위해 항상 Random seed를 고정해두고 개발 한다!!!** 
   
   (주의 할 점은 해당 개발물에 사용되는 난수가 모두 TensorFlow에서 생성된것이 아닐 수 있다는 것이다.) 

In [ ]:
seed = 7777

In [ ]:
tf.random.set_seed(seed)        # random 값을 고정해두고 사용하는 것을 생활화하면 아주좋다.
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)


In [ ]:
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.5411682], shape=(1,), dtype=float32)
tf.Tensor([0.9065834], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)
