# Tensor 연산

In [341]:
import tensorflow as tf

아래의 기본 연산은 `특수 메서드`를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용하는게 가능!

* `tf.add`: 덧셈
* `tf.subtract`: 뺄셈
* `tf.multiply`: 곱셈
* `tf.divide`: 나눗셈
* `tf.pow`: n-제곱
* `tf.negative`: 음수 부호


In [342]:
a = tf.range(6, dtype=tf.int32)   
b = 2 * tf.ones(6, dtype=tf.int32)

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [343]:
print('a : ', a,'\n', 'b : ', b)

print('a + b :',a + b, '\n','tf.add(a,b) : ',tf.add(a,b))       # 텐서끼리 + 를 쓰면, tf의 add를 자동으로 사용한다.

print('a - b :', a-b, '\n','tf.subtract(a,b) : ',tf.subtract(a,b))        # 텐서끼리 - 를 쓰면 tf.subtract와 같음

print('a * b :',a * b, '\n','tf.multiply :',tf.multiply(a,b))        # a * b 는 tf.multiply 와 같다

print('a / b :',a / b,'\n','tf.divide :',tf.divide(a,b))

# print('a // b :', a//b,'\n','tf.truediv :',tf.truediv(a,b))     # 몫 함수는 뭘까?

print('a ** b :',a ** b,'\n','tf.pow :',tf.pow(a,b))

print('-a :',-a,'\n','tf.negative :',tf.negative(a))        # negative 는 인수 하나만 받음

a :  tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 
 b :  tf.Tensor([2 2 2 2 2 2], shape=(6,), dtype=int32)
a + b : tf.Tensor([2 3 4 5 6 7], shape=(6,), dtype=int32) 
 tf.add(a,b) :  tf.Tensor([2 3 4 5 6 7], shape=(6,), dtype=int32)
a - b : tf.Tensor([-2 -1  0  1  2  3], shape=(6,), dtype=int32) 
 tf.subtract(a,b) :  tf.Tensor([-2 -1  0  1  2  3], shape=(6,), dtype=int32)
a * b : tf.Tensor([ 0  2  4  6  8 10], shape=(6,), dtype=int32) 
 tf.multiply : tf.Tensor([ 0  2  4  6  8 10], shape=(6,), dtype=int32)
a / b : tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float64) 
 tf.divide : tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float64)
a ** b : tf.Tensor([ 0  1  4  9 16 25], shape=(6,), dtype=int32) 
 tf.pow : tf.Tensor([ 0  1  4  9 16 25], shape=(6,), dtype=int32)
-a : tf.Tensor([ 0 -1 -2 -3 -4 -5], shape=(6,), dtype=int32) 
 tf.negative : tf.Tensor([ 0 -1 -2 -3 -4 -5], shape=(6,), dtype=int32)


**여러가지 연산**

* `tf.abs`: 절대값
* `tf.sign`: 부호
* `tf.round`: 반올림
* `tf.ceil`: 올림 // 지금 적용안됨 ( 함수 없음 )
* `tf.floor`: 내림
* `tf.square`: 제곱
* `tf.sqrt`: 제곱근 // 들어가는 인수는 float 형식으로 들어가야만 한다.
* `tf.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `tf.cumsum`: 누적합
* `tf.cumprod`: 누적곱


In [344]:
test_zeros = tf.zeros(6)

print(a,b,test_zeros)
print(tf.abs(a,b))
print(tf.sign(a,b), tf.sign(test_zeros))     # 부호 : 0,1로 이루어짐 (?) // True, False 판별하는 것과 비슷한듯.
print(tf.round(tf.divide(a,b)))     # 반올림 // round 안에 divide 를 해도 되는구나
print('ceil', tf.math.ceil(tf.math.divide(a,b)))        # 올림 적용  
print(tf.floor(tf.divide(a,b)))
print(tf.square(a,b))
print(tf.sqrt([[4.], [16.]]))       # 들어가는 인수는 무조건 float 형식으로 해야되는 듯
print(tf.sqrt([[4., 9., 16., 25.]]))    # 1,4 shape

print(tf.maximum(a,b))              # 두 배열(?)에서 각 열의 최댓값을 출력한다. // 각 원소에서!
print(tf.minimum(a,b))              # 두 텐서의 각 원소에서 최솟값만 반환
# print(tf.cumsum(a,b))
print(tf.cumsum(a))                 # 인수를 하나만 받는다.
print(tf.math.cumprod(b))           # 누적 곱 // math 안에 있다.

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) tf.Tensor([2 2 2 2 2 2], shape=(6,), dtype=int32) tf.Tensor([0. 0. 0. 0. 0. 0.], shape=(6,), dtype=float32)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([0 1 1 1 1 1], shape=(6,), dtype=int32) tf.Tensor([0. 0. 0. 0. 0. 0.], shape=(6,), dtype=float32)
tf.Tensor([0. 0. 1. 2. 2. 2.], shape=(6,), dtype=float64)
ceil tf.Tensor([0. 1. 1. 2. 2. 3.], shape=(6,), dtype=float64)
tf.Tensor([0. 0. 1. 1. 2. 2.], shape=(6,), dtype=float64)
tf.Tensor([ 0  1  4  9 16 25], shape=(6,), dtype=int32)
tf.Tensor(
[[2.]
 [4.]], shape=(2, 1), dtype=float32)
tf.Tensor([[2. 3. 4. 5.]], shape=(1, 4), dtype=float32)
tf.Tensor([2 2 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([0 1 2 2 2 2], shape=(6,), dtype=int32)
tf.Tensor([ 0  1  3  6 10 15], shape=(6,), dtype=int32)
tf.Tensor([ 2  4  8 16 32 64], shape=(6,), dtype=int32)


#### Axis 이해하기

In [345]:
rank_2 = tf.random.normal((3, 3))       # 해당 변수를 실행할 때마다 값이 변함

In [346]:
rank_2      # 변수만 불러올때는 값이 변하지 않는다.

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.4894471 , -1.666166  ,  0.19173218],
       [-0.25659904,  1.1539693 ,  1.0813972 ],
       [ 0.9014378 ,  0.0375339 , -0.855405  ]], dtype=float32)>

In [347]:
rank_2[0]
print(rank_2[0])
print(rank_2[1])
print(rank_2[2])

tf.Tensor([-0.4894471  -1.666166    0.19173218], shape=(3,), dtype=float32)
tf.Tensor([-0.25659904  1.1539693   1.0813972 ], shape=(3,), dtype=float32)
tf.Tensor([ 0.9014378  0.0375339 -0.855405 ], shape=(3,), dtype=float32)


In [348]:
rank_2[0, 0]
print(rank_2[0,0])
print(rank_2[0,1])
print(rank_2[0,2])

tf.Tensor(-0.4894471, shape=(), dtype=float32)
tf.Tensor(-1.666166, shape=(), dtype=float32)
tf.Tensor(0.19173218, shape=(), dtype=float32)


In [349]:
a = 0; b=0          # a : 행 , b : 열 로 생각하면 편할듯 하다. (?)
print(rank_2[a,b])


tf.Tensor(-0.4894471, shape=(), dtype=float32)


In [350]:
cnt = 0
for a in range(3):
    for b in range(3):
        cnt += 1
        print('{} rank_2[{},{}] : {}'.format(cnt,a,b,rank_2[a,b]))

1 rank_2[0,0] : -0.48944708704948425
2 rank_2[0,1] : -1.6661659479141235
3 rank_2[0,2] : 0.19173218309879303
4 rank_2[1,0] : -0.2565990388393402
5 rank_2[1,1] : 1.1539692878723145
6 rank_2[1,2] : 1.0813971757888794
7 rank_2[2,0] : 0.9014378190040588
8 rank_2[2,1] : 0.03753390163183212
9 rank_2[2,2] : -0.8554049730300903


In [351]:
rank_1 = tf.random.normal([4,2])
print(rank_1)

tf.Tensor(
[[-1.9302989  -0.6909929 ]
 [ 0.25152466  0.71701145]
 [ 1.6800627  -0.43445554]
 [-0.735872   -0.7508017 ]], shape=(4, 2), dtype=float32)


> - `n 차원 (rank)의 원소개수는 각 axis의 곱의 합과 같다.`

In [352]:
rank_3 = tf.random.normal((3, 3, 3))        # 3차원배열

In [353]:
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-2.4984553 , -1.1835488 , -2.4991837 ],
        [ 0.14474142,  0.5528023 ,  0.13862073],
        [-1.5625323 , -1.4267244 ,  0.37605444]],

       [[-0.7794943 ,  2.416881  , -0.4954455 ],
        [ 0.81328714, -0.35699067,  0.65465826],
        [ 0.2603835 ,  0.88298404,  0.55109316]],

       [[-0.39535272, -0.7077691 , -0.8026535 ],
        [ 0.7000134 ,  1.2630111 ,  0.29688412],
        [ 0.12176097, -0.58401686,  0.49336472]]], dtype=float32)>

In [354]:
rank_3[1,1,2]
print(rank_3[1,1,2])
print(rank_3[0,0,0])

tf.Tensor(0.65465826, shape=(), dtype=float32)
tf.Tensor(-2.4984553, shape=(), dtype=float32)


In [355]:
a = 3;b=3;c=3;cnt=0
for i in range(a):
    for j in range(b):
        for k in range(c):
            cnt += 1
            print('{} rank_3[{},{},{}] : {}'.format(cnt,i,j,k,rank_3[i,j,k]))

1 rank_3[0,0,0] : -2.498455286026001
2 rank_3[0,0,1] : -1.1835488080978394
3 rank_3[0,0,2] : -2.4991836547851562
4 rank_3[0,1,0] : 0.14474141597747803
5 rank_3[0,1,1] : 0.552802324295044
6 rank_3[0,1,2] : 0.13862073421478271
7 rank_3[0,2,0] : -1.5625323057174683
8 rank_3[0,2,1] : -1.4267244338989258
9 rank_3[0,2,2] : 0.37605443596839905
10 rank_3[1,0,0] : -0.7794942855834961
11 rank_3[1,0,1] : 2.4168810844421387
12 rank_3[1,0,2] : -0.49544548988342285
13 rank_3[1,1,0] : 0.8132871389389038
14 rank_3[1,1,1] : -0.35699066519737244
15 rank_3[1,1,2] : 0.6546582579612732
16 rank_3[1,2,0] : 0.2603834867477417
17 rank_3[1,2,1] : 0.8829840421676636
18 rank_3[1,2,2] : 0.5510931611061096
19 rank_3[2,0,0] : -0.39535272121429443
20 rank_3[2,0,1] : -0.7077690958976746
21 rank_3[2,0,2] : -0.8026534914970398
22 rank_3[2,1,0] : 0.7000133991241455
23 rank_3[2,1,1] : 1.26301109790802
24 rank_3[2,1,2] : 0.29688411951065063
25 rank_3[2,2,0] : 0.12176097184419632
26 rank_3[2,2,1] : -0.5840168595314026
27 ra

In [356]:
rank_3[2,1,1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.2630111>

In [357]:
rank_4 = tf.random.normal((3, 3, 3, 3))

In [358]:
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[ 3.9733440e-01, -1.2070237e+00, -1.4681974e-01],
         [-1.0910338e+00,  2.1956167e-01,  6.0591072e-01],
         [-1.3998753e+00, -1.8701566e+00,  4.8417634e-01]],

        [[ 5.5450290e-01,  5.8527297e-01,  1.8656762e-01],
         [ 3.3023608e-01, -1.9782463e-01,  3.4158123e-01],
         [ 7.3324907e-01, -5.9036535e-01,  2.7302432e-01]],

        [[ 1.0472624e+00, -1.4896776e-01,  5.8378070e-04],
         [-9.6451646e-01,  1.0827866e+00, -2.6833283e-02],
         [ 3.4341460e-01,  1.3950546e-01, -1.3579055e+00]]],


       [[[ 5.0574803e-01,  7.8295243e-01, -1.1838249e-01],
         [ 1.3612683e+00, -1.7083265e+00,  1.0575427e+00],
         [ 7.7085072e-01,  1.4854984e+00,  1.1013290e-01]],

        [[-1.4217014e+00, -1.9085101e+00, -1.9654737e-01],
         [ 4.9273959e-01,  9.0498537e-01,  1.4785470e+00],
         [-2.9483306e-01,  1.6719249e+00, -6.9203901e-01]],

        [[-1.8429416e+00, -1.5540247e+00, -1.7094

In [359]:
print(rank_4[0,0,0,0])

tf.Tensor(0.3973344, shape=(), dtype=float32)


In [360]:
cnt = 0
for a in range(3):
    for b in range(3):
        for c in range(3):
            for d in range(3):
                cnt += 1
                print('{} rank_4[{},{},{},{}] : {}'.format(cnt,a,b,c,d,rank_4[a,b,c,d]))

1 rank_4[0,0,0,0] : 0.39733439683914185
2 rank_4[0,0,0,1] : -1.2070237398147583
3 rank_4[0,0,0,2] : -0.14681974053382874
4 rank_4[0,0,1,0] : -1.0910338163375854
5 rank_4[0,0,1,1] : 0.21956166625022888
6 rank_4[0,0,1,2] : 0.6059107184410095
7 rank_4[0,0,2,0] : -1.399875283241272
8 rank_4[0,0,2,1] : -1.8701566457748413
9 rank_4[0,0,2,2] : 0.4841763377189636
10 rank_4[0,1,0,0] : 0.5545029044151306
11 rank_4[0,1,0,1] : 0.5852729678153992
12 rank_4[0,1,0,2] : 0.18656761944293976
13 rank_4[0,1,1,0] : 0.3302360773086548
14 rank_4[0,1,1,1] : -0.197824627161026
15 rank_4[0,1,1,2] : 0.34158122539520264
16 rank_4[0,1,2,0] : 0.7332490682601929
17 rank_4[0,1,2,1] : -0.5903653502464294
18 rank_4[0,1,2,2] : 0.273024320602417
19 rank_4[0,2,0,0] : 1.04726243019104
20 rank_4[0,2,0,1] : -0.14896775782108307
21 rank_4[0,2,0,2] : 0.0005837806966155767
22 rank_4[0,2,1,0] : -0.9645164608955383
23 rank_4[0,2,1,1] : 1.0827865600585938
24 rank_4[0,2,1,2] : -0.02683328278362751
25 rank_4[0,2,2,0] : 0.34341460466

**차원 축소 연산**

* `tf.reduce_mean`: 설정한 축의 평균을 구한다. 
* `tf.reduce_max`: 설정한 축의 최댓값을 구한다. 
* `tf.reduce_min`: 설정한 축의 최솟값을 구한다. 
* `tf.reduce_prod`: 설정한 축의 요소를 모두 곱한 값을 구한다. 
* `tf.reduce_sum`: 설정한 축의 요소를 모두 더한 값을 구한다. 

In [361]:
a = tf.range(6)
a       # vector 배열


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

In [362]:
print(tf.reduce_sum(a))
print(tf.reduce_sum(a, axis=0))

tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


In [363]:
tf.reduce_sum(a, axis=0),

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,)

In [364]:
b = tf.random.normal((2,7))
b

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[-1.5325661 , -0.7937742 , -0.8079839 ,  0.30234125, -0.5484793 ,
         2.0528502 ,  0.35439634],
       [-0.21488234,  1.1746923 ,  0.94725925, -0.5900521 , -0.34858507,
         0.34309196, -2.1474876 ]], dtype=float32)>

In [365]:
tf.reduce_mean(b, axis=0), tf.reduce_mean(b, axis=1)

(<tf.Tensor: shape=(7,), dtype=float32, numpy=
 array([-0.8737242 ,  0.19045904,  0.06963769, -0.14385544, -0.4485322 ,
         1.1979711 , -0.89654565], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.1390308 , -0.11942339], dtype=float32)>)

행렬과 관련된 연산

* `tf.matmul`: 내적
* `tf.linalg.inv`: 역행렬


In [366]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [367]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

**크기 및 차원을 바꾸는 명령**
 (잘 사용됩니다!!)
 
이를 사용 할 때는 축을 잘 이해하고 사용하시면 좋습니다. 

* `tf.reshape`: 벡터 행렬의 크기 변환
* `tf.transpose`: 전치 연산
* `tf.expand_dims`: 지정한 축으로 차원을 추가
* `tf.squeeze`: 벡터로 차원을 축소

In [368]:
a = tf.range(6, dtype=tf.int32)      # [0, 1, 2, 3, 4, 5]
print("a     :", a, "\n")

a_2d = tf.reshape(a, (2, 3))  # 1차원 벡터는 2x3 크기의 2차원 행렬로 변환 // numpy와 동일
print("a_2d  :", a_2d, "\n")

a_2d_t = tf.transpose(a_2d)   # 2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환 // numpy와 동일
print("a_2d_t:", a_2d_t, "\n")

a_3d = tf.expand_dims(a_2d, 0) # 2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
print("a_3d  :", a_3d, "\n")

a_4d = tf.expand_dims(a_3d, 3)# or -1) # 1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
print("a_4d  :", a_4d, "\n")

a_1d = tf.squeeze(a_4d)
print("a_1d  :", a_1d, "\n")   # 1x2x3x1 크기의 4차원 행렬을 1차원 벡터로 변환

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 

a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 

a_2d_t: tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 

a_3d  : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 

a_4d  : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 

a_1d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



**텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

* `tf.slice`: 특정 부분을 추출
* `tf.split`: 분할
* `tf.concat`: 합치기
* `tf.tile`: 복제-붙이기
* `tf.stack`: 합성
* `tf.unstack`: 분리 

In [369]:
a = tf.reshape(tf.range(12), (3, 4))        # shape 는 생략이 가능하다
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [370]:
print(tf.slice(a, [0, 1], [1, 3]))   # (0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.
print(tf.slice(a, [0, 1], [2, 3]))
print(tf.slice(a, [0, 1], [3, 3]))
print(tf.slice(a, [0, 0], [3, 4]))


tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


In [371]:
a[0], a[1]

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>)

In [372]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)  # 가로축(axis=1)을 따라 2개로 분할 
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [373]:
tf.concat([a1, a2], axis=1) # 가로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [374]:
tf.tile(a1, [1, 3])  # 가로축(axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]], dtype=int32)>

In [375]:
a3 = tf.stack([a1, a2])  # 3x2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]], dtype=int32)>

In [376]:
tf.unstack(a3, axis=1)  # 2x3x2 고차원 텐서를 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]], dtype=int32)>]

#### 간단 퀴즈

다음 코드를 에러 없이 실행하라. 

In [385]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
b = tf.constant([1, 2, 3])

# tf.matmul(a, b)
tf.matmul(a, tf.expand_dims(b,axis=1))

# b의 dim을 추가하면 된다. // expand_dims

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]], dtype=int32)>

-----